### ISSUE TITLE
Query REST Function

### ISSUE THREAD

**Issue by ericderegt** [NYU-DevOps-Spring2018-Orders/orders#9] opened 2018-02-20 18:56 UTC
**As a** user  
**I need** to access a query endpoint   
**So that** I can find orders  

**Assumptions:**
* /orders/<int:id> is the route

**Acceptance Criteria:**
```
When I run the service locally and request /orders/id,
an individual order should be returned.

Rest function should also be set up with a test case to ensure function is working properly
```

**Comment by hjcho7311** [comment] 2018-03-02 06:41
Duplicate of Issue #24

**Comment by hjcho7311** [comment] 2018-03-02 21:03
reworking for this issue... closed #24

**Closed** 2018-04-09 17:27 UTC
Labels: enhancement
